defaults:
  - optimizer: adam_8bit
  - peft: dev

# clip:
#   active: False
#   epochs: 2
#   batch_size: 4
#   shuffle_buffer_size: 16
#   prefetch_buffer_size: 1
#   data_dir: processed
#   use_context: True

# vqa:
#   active: True
#   epochs: 2
#   batch_size: 2
#   optimizer_step_freq: 32
#   shuffle_buffer_size: 16
#   prefetch_buffer_size: 1
#   loss_function: builtin
#   data_dir: processed
#   use_context: True
#   clip_eval: False

bc:
  active: True
  epochs: 2
  batch_size: 4
  optimizer_step_freq: 4
  shuffle_buffer_size: 256
  loss_function: builtin
  # loss_function_kwargs:
  #   reduction: mean
  clip_eval: False
  clip_checkpoint: fresh-snowball-80-clip.pt
  copy_each_epoch: False

device:
  gpu: True
